language: node_js
node_js:
- "node"
cache:
  directories:
    - "node_modules"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: cd API && npm run test
after_success: cd API && npm run coverage
